In [1]:
import numpy as np

In [2]:
weight_vector = np.array([[1], [1],[1]])
x_vector = np.array([[3], [4], [5]])

In [3]:
weight_vector

array([[1],
       [1],
       [1]])

In [4]:
x_vector

array([[3],
       [4],
       [5]])

In [5]:
weight_vector.T

array([[1, 1, 1]])

In [6]:
weight_vector.T.dot(x_vector)

array([[12]])

In [7]:
import pandas as pd

In [8]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [9]:
df_data.values[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00, 2.400e+01])

In [10]:
df_data['weight_0'] = 1
df_data = df_data.drop("MEDV", axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [11]:
df_data.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [12]:
df_data.shape

(506, 14)

In [13]:
df_matrix = df_data.values
weight_vector = np.random.random_sample((14, 1))

In [14]:
weight_vector

array([[0.79838915],
       [0.21500804],
       [0.23762553],
       [0.68703222],
       [0.71268653],
       [0.54007626],
       [0.10245829],
       [0.64116817],
       [0.19936563],
       [0.70900771],
       [0.55566919],
       [0.16134522],
       [0.71056303],
       [0.89455155]])

In [15]:
df_matrix.dot(weight_vector)

array([[304.69965029],
       [270.06912609],
       [264.37031865],
       [248.2733047 ],
       [251.30820992],
       [250.81693342],
       [322.13694375],
       [330.52558088],
       [336.77346324],
       [326.72073589],
       [330.98708485],
       [325.06245866],
       [320.68456269],
       [316.31722828],
       [317.26911731],
       [315.51895469],
       [310.36922001],
       [321.13038043],
       [298.04946703],
       [317.66472955],
       [325.53182666],
       [322.11770998],
       [326.93021487],
       [327.9274233 ],
       [324.81018895],
       [309.36268131],
       [320.60519802],
       [311.03820055],
       [321.68481917],
       [319.27230399],
       [323.85823547],
       [320.67710071],
       [305.84418097],
       [320.42905239],
       [304.77944955],
       [295.45910387],
       [292.85940484],
       [292.41274545],
       [291.74417098],
       [283.64607401],
       [281.60344444],
       [251.94563678],
       [252.37147386],
       [255