In [2]:
import numpy as np

In [3]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array[3])

numpy.float64

In [5]:
test_array.shape

(4,)

In [6]:
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [11]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
matrix = np.array(matrix, int)
matrix

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [12]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

In [14]:
np.array(tensor, int)

array([[[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]]])

In [15]:
np.array(tensor, int).shape

(4, 3, 4)

In [16]:
np.array(matrix, int).ndim

2

In [18]:
np.array(tensor, int).size

48

In [19]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [20]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [21]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [22]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [23]:
np.array(test_matrix).reshape(2,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [24]:
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [25]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [26]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

In [27]:
a = np.array(test_matrix).reshape(2,2,2)
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [28]:
a.shape

(2, 2, 2)

In [29]:
a.size

8

In [33]:
a.reshape(-1, 4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [34]:
a.reshape(-1, 4).shape

(2, 4)

In [35]:
a.reshape(-1,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [36]:
a[0,0]

array([1, 2])

In [37]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [38]:
a[0,0,1]

2

In [39]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)

In [40]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [42]:
a[1,1:3]

array([7, 8])

In [43]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [44]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
np.arange(0, 5, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8])

In [46]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [48]:
np.arange(30).reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [70]:
np.empty(shape=(10,), dtype=np.int8)

array([-80,  78, -79,  21, -91,   1,   0,   0,   0,   0], dtype=int8)

TypeError: zeros() missing required argument 'shape' (pos 1)